# 2021/9/7
## 本代码修改domain文件
## 更改海陆分布

In [1]:
import xarray as xr
import numpy as np
path = "/home/sun/data/domain/"
f1   =  xr.open_dataset(path+"domain.lnd.fv0.9x1.25_gx1v7.151020.nc")
f2   =  xr.open_dataset(path+"domain.ocn.gx1v7.151008.nc")
f3   =  xr.open_dataset(path+"domain.ocn.1x1.111007.nc")

mask_zero = f1.mask.data[60,1]
frac_zero = f1.frac.data[60,1]
mask_one  = f2.mask.data[60,1]
frac_one  = f2.frac.data[60,1]

**这里针对mask和frac变量进行修改**

In [2]:
for i in range(0,192):
    for j in range(0,288):
        if 70<=f1.xc.data[i,j]<=90:
            if 0<=f1.yc.data[i,j]<=20:
                f1.mask.data[i,j] = mask_zero
                f1.frac.data[i,j] = frac_zero
            else:
                continue
        else:
            continue
for i in range(0,384):
    for j in range(0,320):
        if 70<=f2.xc.data[i,j]<=90:
            if 0<=f2.yc.data[i,j]<=20:
                f2.mask.data[i,j] = mask_one
                f2.frac.data[i,j] = frac_one
            else:
                continue
        else:
            continue

In [3]:
f1.to_netcdf("/home/sun/data/domain/domain.lnd.changed.nc")
f2.to_netcdf(path+"domain.ocn.gx1v7.changed.nc")

In [4]:
del f1 ; del f2

In [9]:
path = "/home/sun/data/domain/"
f1   =  xr.open_dataset(path+"domain.lnd.changed.nc")
f2   =  xr.open_dataset(path+"domain.ocn.gx1v7.changed.nc")

In [10]:
f1.mask[90,70:90]

<xarray.DataArray 'mask' (ni: 20)>
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int32)
Coordinates:
    xc       (ni) float64 ...
    yc       (ni) float64 ...
Dimensions without coordinates: ni
Attributes:
    long_name:  domain mask
    note:       unitless
    comment:    0 value indicates cell is not active

In [40]:
f2.xc[70,98:116]

<xarray.DataArray 'xc' (ni: 18)>
array([70.812502, 71.937502, 73.062502, 74.187502, 75.312502, 76.437502,
       77.562502, 78.687502, 79.812502, 80.937502, 82.062502, 83.187502,
       84.312502, 85.437502, 86.562502, 87.687502, 88.812502, 89.937503])
Coordinates:
    xc       (ni) float64 ...
    yc       (ni) float64 ...
Dimensions without coordinates: ni
Attributes:
    long_name:  longitude of grid cell center
    units:      degrees_east
    bounds:     xv

In [33]:
f2.yc[190:250,50]

<xarray.DataArray 'yc' (nj: 60)>
array([ 0.933971,  1.200496,  1.466873,  1.733102,  1.999181,  2.265109,
        2.530887,  2.796513,  3.061987,  3.327307,  3.592473,  3.857485,
        4.12234 ,  4.38704 ,  4.651582,  4.915966,  5.180192,  5.444259,
        5.708165,  5.97191 ,  6.235494,  6.498916,  6.762175,  7.02527 ,
        7.2882  ,  7.550966,  7.813565,  8.075998,  8.338264,  8.600362,
        8.862291,  9.12411 ,  9.385993,  9.648173,  9.910883, 10.174358,
       10.43883 , 10.704535, 10.97171 , 11.240592, 11.511422, 11.784442,
       12.059898, 12.338037, 12.619109, 12.90337 , 13.191075, 13.482482,
       13.777855, 14.077455, 14.381551, 14.690407, 15.004292, 15.323474,
       15.648217, 15.978784, 16.315434, 16.658417, 17.007979, 17.364349])
Coordinates:
    xc       (nj) float64 ...
    yc       (nj) float64 ...
Dimensions without coordinates: nj
Attributes:
    long_name:  latitude of grid cell center
    units:      degrees_north
    bounds:     yv

In [26]:
f1.frac[96:117,56:73].data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [42]:
f2.frac[190:250,98:110].data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.,